CarPooling/CarPooling/Controllers/FeedbackController.cs
using CarPooling.Data;
using CarPooling.Services.DTOs.CreateDTOs;
using CarPooling.Services.DTOs.PresentDTOs;
using CarPooling.Services.Services.Contracts;
using CarPooling.Web.Helpers;
using CarPooling.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarPooling.Web.Controllers
{
    [CustomAuthorization(Role = "User")]
    public class FeedbackController : Controller
    {
        private readonly IFeedbackService feedbackService;

        public FeedbackController(IFeedbackService feedbackService)
        {
            this.feedbackService = feedbackService;
        }

        public async Task<IActionResult> Index(int userId, string sortOrder, string name, string rating, string comment, int pagenumber = 1)
        {
            var feedbacks = await this.GetFeedbacks(userId, sortOrder, name, rating, comment, pagenumber);

            return this.View(feedbacks);
        }

        public async Task<IActionResult> ViewUserFeedback(int userId, string sortOrder, string name, string rating, string comment, int pagenumber = 1)
        {
            var feedbacks = await this.GetFeedbacks(userId, sortOrder, name, rating, comment, pagenumber);

            return this.View(feedbacks);
        }

        //GET-Create
        public IActionResult CreateFeedback(string toUserId, string travelId)
        {
            ViewBag.ToUserId = toUserId;
            ViewBag.TravelId = travelId;

            var feedback = new FeedbackCreateDTO();

            return this.View(feedback);
        }

        //Post-Create
        [HttpPost]
        public async Task<IActionResult> CreateFeedbackPost(FeedbackCreateDTO feedbackCreate, int travelId, string toUserId)
        {
            if (!this.ModelState.IsValid)
            {
                ViewBag.ToUserId = toUserId;
                ViewBag.TravelId = travelId;

                return this.View("CreateFeedback", feedbackCreate);
            }

            await this.feedbackService.CreateAsync(feedbackCreate, travelId);

            return this.RedirectToAction("Index", "Home");
        }

        private async Task<PaginatedList<FeedbackPresentDTO>> GetFeedbacks(int userId, string sortOrder, string name, string rating, string comment, int pagenumber = 1)
        {
            this.SetViewBags(userId, sortOrder, name, rating, comment);

            var feedbacks = await this.feedbackService.FilterByMultipleCriteria(userId, name, rating, comment);

            feedbacks = Sort(feedbacks, sortOrder);

            return PaginatedList<FeedbackPresentDTO>.Create(feedbacks, pagenumber, 10);
        }

        private void SetViewBags(int userId, string sortOrder, string name, string rating, string comment)
        {
            ViewBag.SortOrder = sortOrder;
            ViewBag.NameSortParm = sortOrder == "name" ? "name_desc" : "name";
            ViewBag.RatingSortParm = string.IsNullOrEmpty(sortOrder) ? "rating_desc" : "";
            ViewBag.Name = name;
            ViewBag.Rating = rating;
            ViewBag.Comment = comment;
            ViewData["UserFeedbackNavigationId"] = userId;
        }

        private static IEnumerable<FeedbackPresentDTO> Sort(IEnumerable<FeedbackPresentDTO> list, string sortOrder)
        {
            list = sortOrder switch
            {
                "name" => list.OrderBy(s => s.FromUser),
                "name_desc" => list.OrderByDescending(s => s.FromUser),
                "rating_desc" => list.OrderByDescending(s => s.Rating),
                _ => list.OrderBy(s => s.Rating),
            };
            return list;
        }
    }
}

CarPooling/CarPooling/Controllers/MyTravelsController.cs
using CarPooling.Services.DTOs.PresentDTOs;
using CarPooling.Services.Exceptions;
using CarPooling.Services.Services.Contracts;
using CarPooling.Web.Helpers;
using CarPooling.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarPooling.Web.Controllers
{
    [CustomAuthorization(Role = "User")]
    public class MyTravelsController : Controller
    {
        private readonly ITravelService travelService;
        private readonly IUserService userService;

        public MyTravelsController(ITravelService travelService, IUserService userService)
        {
            this.travelService = travelService;
            this.userService = userService;
        }

        public async Task<IActionResult> OrganizedTravels(int id, string sortOrder, string startingCity, string endingCity,
                                                string user, DateTime? departureTime, string seats, string status, int pagenumber = 1)
        {
            var organizedTravels = await this.travelService.GetOrganizedTravelsAsync(id, "Available");

            var filteredTravels = this.Filter(organizedTravels, sortOrder, id, startingCity, endingCity, user, departureTime, seats, status, pagenumber);


            return View(filteredTravels);
        }

        public async Task<IActionResult> PendingPassengers(int id)
        {
            var pendingPassengers = await this.travelService.ListPendingPassengersForTravel(id);

            this.HttpContext.Session.SetString("CurrentTravelId", id.ToString());

            return View(pendingPassengers);
        }

        public async Task<IActionResult> ApprovedPassengers(int id)
        {
            var approvedPassengers = await this.travelService.ListApprovedPassengersForTravel(id);

            this.HttpContext.Session.SetString("CurrentTravelId", id.ToString());

            return View(approvedPassengers);
        }

        public async Task<IActionResult> Approve(int id)
        {
            var userToApprove = await this.userService.GetAsync(id);

            return View(userToApprove);
        }

        [HttpPost]
        public async Task<IActionResult> ApprovePost(int travelId, int passengerId)
        {
            await this.travelService.ApprovePassengerForTravel(passengerId, travelId);

            return this.RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Decline(int id)
        {
            var userToDecline = await this.userService.GetAsync(id);

            return View(userToDecline);
        }

        [HttpPost]
        public async Task<IActionResult> DeclinePost(int travelId, int passengerId)
        {
            await this.travelService.DeclinePassengerFromTravel(passengerId, travelId);

            return this.RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Reject(int id)
        {
            var userToReject = await this.userService.GetAsync(id);

            return View(userToReject);
        }

        [HttpPost]
        public async Task<IActionResult> RejectPost(int travelId, int passengerId, int driverId)
        {
            await this.travelService.RejectParticipationInTravel(passengerId, travelId, driverId);

            return this.RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> PendingTravels(int userId)
        {
            var pendingTravels = await this.travelService.ListPendingTravelsAsync(userId);

            return View(pendingTravels);
        }

        public async Task<IActionResult> ApprovedTravels(int userId)
        {
            var approvedTravels = await this.travelService.ListApprovedTravelsAsync(userId, "Available");

            return View(approvedTravels);
        }

        public async Task<IActionResult> Cancel(int travelId)
        {
            var travelToCancel = await this.travelService.GetAsync(travelId);

            return View(travelToCancel);
        }

        [HttpPost]
        public async Task<IActionResult> CancelPost(int travelId, int userId)
        {
            await this.travelService.CancelParticipationInTravel(userId, travelId);

            return this.RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> CancelTrip(int travelId)
        {
            var travelToCancel = await this.travelService.GetAsync(travelId);

            return View(travelToCancel);
        }

        [HttpPost]
        public async Task<IActionResult> CancelTripPost(int travelId, int userId)
        {
            try
            {
                await this.travelService.CancelTrip(userId, travelId);
            }
            catch (BlockedStateException x)
            {
                var travelToCancel = await this.travelService.GetAsync(travelId);
                this.ModelState.AddModelError("DepartureTime", x.Message);
                return this.View("CancelTrip", travelToCancel);
            }

            return this.RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> MarkAsComplete(int travelId)
        {
            var travelToComplete = await this.travelService.GetAsync(travelId);

            return View(travelToComplete);
        }

        [HttpPost]
        public async Task<IActionResult> MarkAsCompletePost(int travelId, int driverId)
        {
            try
            {
                await this.travelService.MarkTripAsComplete(driverId, travelId);
            }
            catch (BlockedStateException x)
            {
                var travelToComplete = await this.travelService.GetAsync(travelId);
                this.ModelState.AddModelError("DepartureTime", x.Message);
                return this.View("MarkAsComplete", travelToComplete);
            }

            return this.RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> PastOrganizedTravels(int id)
        {
            var pastOrganizedTravels = await this.travelService.GetOrganizedTravelsAsync(id, "Completed");

            return View(pastOrganizedTravels);
        }

        public async Task<IActionResult> PastApprovedTravels(int userId)
        {
            var pastApprovedTravels = await this.travelService.ListApprovedTravelsAsync(userId, "Completed");

            return View(pastApprovedTravels);
        }

        public async Task<IActionResult> PastApprovedPassengers(int id)
        {
            var pastApprovedPassengers = await this.travelService.ListApprovedPassengersForTravel(id);

            ViewBag.TravelId = id.ToString();

            this.HttpContext.Session.SetString("CurrentTravelId", id.ToString());

            return View(pastApprovedPassengers);
        }

        private PaginatedList<TravelPresentDTO> Filter(IEnumerable<TravelPresentDTO> travels,
                                                         string sortOrder, int id, string startingCity, string endingCity,
                                                         string user, DateTime? departureTime, string seats, string status, int pagenumber = 1)
        {
            this.SetViewBags(id, sortOrder, startingCity, endingCity, user, departureTime, seats, status);

            var filteredTravels = this.travelService.FilterByMultipleCriteria(travels, startingCity, endingCity, user, departureTime, seats, default, status);

            filteredTravels = Sort(filteredTravels, sortOrder);

            return PaginatedList<TravelPresentDTO>.Create(filteredTravels, pagenumber, 5);
        }

        private static IEnumerable<TravelPresentDTO> Sort(IEnumerable<TravelPresentDTO> list, string sortOrder)
        {
            list = sortOrder switch
            {
                "name" => list.OrderBy(s => s.CreatedByUser),
                "name_desc" => list.OrderByDescending(s => s.CreatedByUser),
                "status" => list.OrderBy(s => s.Status),
                "status_desc" => list.OrderByDescending(s => s.Status),
                "startingCity_desc" => list.OrderByDescending(s => s.StartingPoint),
                "endingCity" => list.OrderBy(s => s.EndingPoint),
                "endingCity_desc" => list.OrderByDescending(s => s.EndingPoint),
                "departureTime" => list.OrderBy(s => s.DepartureTime),
                "departureTime_desc" => list.OrderByDescending(s => s.DepartureTime),
                "seats" => list.OrderBy(s => s.FreeSeats),
                "seats_desc" => list.OrderByDescending(s => s.FreeSeats),
                _ => list.OrderBy(s => s.StartingPoint),
            };
            return list;
        }

        private void SetViewBags(int id, string sortOrder, string startingCity, string endingCity, string user, DateTime? departureTime, string seats, string status)
        {
            ViewBag.SortOrder = sortOrder;
            ViewBag.StartSort = String.IsNullOrEmpty(sortOrder) ? "startingCity_desc" : "";
            ViewBag.EndSort = sortOrder == "endingCity" ? "endingCity_desc" : "endingCity";
            ViewBag.NameSort = sortOrder == "name" ? "name_desc" : "name";
            ViewBag.DepartureSort = sortOrder == "departureTime" ? "departureTime_desc" : "departureTime";
            ViewBag.SeatSort = sortOrder == "seats" ? "seats_desc" : "seats";
            ViewBag.StatusSort = sortOrder == "status" ? "status_desc" : "status";
            ViewBag.TravelId = id;
            ViewBag.StartingCity = startingCity;
            ViewBag.EndingCity = endingCity;
            ViewBag.User = user;
            ViewBag.DepartureTime = departureTime;
            ViewBag.Seats = seats;
            ViewBag.Status = status;

        }

    }
}

CarPooling/CarPooling/Views/MyTravels/Approve.cshtml
@{
    ViewData["Title"] = "Approve Passenger";
    this.ViewData["CurrentUserId"] = this.Context.Session.GetString("CurrentUserId");
    this.ViewData["CurrentTravelId"] = this.Context.Session.GetString("CurrentTravelId");
}

@model CarPooling.Services.DTOs.PresentDTOs.UserPresentDTO

<div id="wrapper" class="toggled">

    <!-- Sidebar -->
    <partial name="_Sidebar.cshtml" />
    <!-- /#sidebar-wrapper -->
    <!-- Page Content -->
    <div id="page-content-wrapper">
        <form method="post" asp-action="ApprovePost" class="text-center">
            <input asp-for="Id" hidden />
            <div class="border p-4">
                <div class="form-group row mt-5">
                    <h1 class="text-primary pb-3 text-center">
                        Approve User
                    </h1>
                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <div class="form-group row">
                            <div class="col d-flex justify-content-center">
                                <label asp-for="FirstName">First name</label>
                            </div>
                            <div class="col d-flex justify-content-center">
                                <label asp-for="LastName">Last name</label>
                            </div>
                            <div class="col d-flex justify-content-center">
                                <label asp-for="Email">Email</label>
                            </div>
                            <div class="col d-flex justify-content-center">
                                <label asp-for="PhoneNumber">Phone Number</label>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col p-3">
                                <input asp-for="FirstName" disabled class="form-control" />
                                <span asp-validation-for="FirstName" class="text-danger"></span>
                            </div>
                            <div class="col p-3">
                                <input asp-for="LastName" disabled class="form-control" />
                                <span asp-validation-for="LastName" class="text-danger"></span>
                            </div>
                            <div class="col p-3">
                                <input asp-for="Email" disabled class="form-control" />
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>
                            <div class="col p-3">
                                <input asp-for="PhoneNumber" disabled class="form-control" />
                                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row pt-5">
                            <div class="col-6 text-center">
                                <a asp-controller="Home" asp-action="Index" class="btn btn-secondary">Back to Home</a>
                            </div>
                            <div class="col-4 text-center">
                                <input type="submit" value="Approve" class="btn btn-success" asp-controller="MyTravels" asp-action="ApprovePost" asp-route-passengerId="@Model.Id" asp-route-travelId="@this.ViewData["CurrentTravelId"]">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <!-- /#page-content-wrapper -->

</div>

CarPooling/CarPooling/Views/MyTravels/ApprovedPassengers.cshtml
@{
    ViewData["Title"] = "Approved Passengers";
    this.ViewData["CurrentUserId"] = this.Context.Session.GetString("CurrentUserId");
}

@model IEnumerable<CarPooling.Services.DTOs.PresentDTOs.UserPresentDTO>
<div id="wrapper" class="toggled">

    <!-- Sidebar -->
    <partial name="_Sidebar.cshtml" />
    <!-- /#sidebar-wrapper -->
    <!-- Page Content -->
    <div id="page-content-wrapper">
        <h1 class="text-primary pb-3 text-center">
            Manage Approved Passengers
        </h1>
        <div class="main">
            @if (Model.Count() == 0)
            {
                <h4 class="text-center">No approved passengers for this travel yet.</h4>
            }
            else
            {
                <table class="table table-style text-center">
                    <thead>
                        <tr>
                            <th scope="col">Profile</th>
                            <th scope="col">First Name</th>
                            <th scope="col">Last Name</th>
                            <th scope="col">Username</th>
                            <th scope="col">Email</th>
                            <th scope="col">Phone number</th>
                            <th>Manage</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var user in Model)
                        {
                            <tr>
                                <td>
                                    <img src="~/profile-pictures/@user.ProfilePicture"
                                         class="rounded-circle"
                                         height="40" width="40"
                                         asp-append-version="true" />
                                </td>
                                <td>@user.FirstName</td>
                                <td>@user.LastName</td>
                                <td><a asp-controller="User" asp-action="ViewUserProfile" asp-route-userId="@user.Id">@user.Username</a></td>
                                <td>@user.Email</td>
                                <td>@user.PhoneNumber</td>
                                <td width="8%">
                                    <div class="w-100 btn-group" role="group">
                                        <a asp-controller="MyTravels" asp-action="Reject" asp-route-id="@user.Id" class="btn btn-danger d-flex justify-content-center mx-1">Reject</a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            <div class="d-flex justify-content-center">
                <a asp-controller="Home" asp-action="Index" class="btn btn-secondary d-flex justify-content-center mx-1 mt-3">Back to Home</a>
            </div>
        </div>
    </div>
    <!-- /#page-content-wrapper -->

</div>

CarPooling/CarPooling/Views/MyTravels/ApprovedTravels.cshtml
@{
    ViewData["Title"] = "My Approved Travels";
}

@model IEnumerable<CarPooling.Services.DTOs.PresentDTOs.TravelPresentDTO>
<div id="wrapper" class="toggled">

    <!-- Sidebar -->
    <partial name="_Sidebar.cshtml" />
    <!-- /#sidebar-wrapper -->
    <!-- Page Content -->
    <div id="page-content-wrapper">
        <h1 class="text-primary pb-3 text-center">
            My Approved Travels
        </h1>
        <div class="main">
            @if (Model.Count() == 0)
            {
                <h4 class="text-center">No approved travels yet.</h4>
            }
            else
            {
                <table class="table table-style text-center">
                    <thead>
                        <tr>
                            <th scope="col">Starting Point</th>
                            <th scope="col">Ending Point</th>
                            <th scope="col">DepartureTime</th>
                            <th scope="col">Created By User</th>
                            <th scope="col">Free Seats</th>
                            <th scope="col">Status</th>
                            <th>Manage</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var travel in Model)
                        {
                            <tr>
                                <td>@travel.StartingPoint</td>
                                <td>@travel.EndingPoint</td>
                                <td>@travel.DepartureTime</td>
                                <td><a asp-controller="User" asp-action="ViewUserProfile" asp-route-userId="@travel.CreatedByUserId">@travel.CreatedByUser</a></td>
                                <td>@travel.FreeSeats</td>
                                <td>@travel.Status</td>
                                <td width="7%">
                                    <a asp-controller="MyTravels" asp-action="Cancel" asp-route-travelId="@travel.Id" class="btn btn-warning d-flex justify-content-center">Cancel</a>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            <div class="d-flex justify-content-center">
                <a asp-controller="Home" asp-action="Index" class="btn btn-secondary d-flex justify-content-center mx-1 mt-3">Back to Home</a>
            </div>
        </div>
    </div>
    <!-- /#page-content-wrapper -->

</div>

CarPooling/CarPooling/Views/MyTravels/Cancel.cshtml
@{
    ViewData["Title"] = "Cancel Participation";
    this.ViewData["CurrentUserId"] = this.Context.Session.GetString("CurrentUserId");
}

@model CarPooling.Services.DTOs.PresentDTOs.TravelPresentDTO
<div id="wrapper" class="toggled">

    <!-- Sidebar -->
    <partial name="_Sidebar.cshtml" />
    <!-- /#sidebar-wrapper -->
    <!-- Page Content -->
    <div id="page-content-wrapper">
        <form method="post" asp-action="CancelPost" class="text-center">
            <div class="border p-4">
                <div class="form-group row mt-5">
                    <h1 class="text-primary pb-3 text-center">
                        Cancel Participation In Travel
                    </h1>
                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <div class="form-group row">
                            <div class="col d-flex justify-content-center">
                                <label asp-for="StartingPoint">Starting Point</label>
                            </div>
                            <div class="col d-flex justify-content-center">
                                <label asp-for="EndingPoint">Ending Point</label>
                            </div>
                            <div class="col d-flex justify-content-center">
                                <label asp-for="DepartureTime">DepartureTime</label>
                            </div>
                            <div class="col d-flex justify-content-center">
                                <label asp-for="FreeSeats">Free Seats</label>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col p-3">
                                <input asp-for="StartingPoint" disabled class="form-control" />
                            </div>
                            <div class="col p-3">
                                <input asp-for="EndingPoint" disabled class="form-control" />
                            </div>
                            <div class="col p-3">
                                <input asp-for="DepartureTime" disabled class="form-control" />
                            </div>
                            <div class="col p-3">
                                <input asp-for="FreeSeats" disabled class="form-control" />
                            </div>
                        </div>

                        <div class="row pt-5">
                            <div class="col-6 text-center">
                                <a asp-controller="Home" asp-action="Index" class="btn btn-secondary">Back to Home</a>
                            </div>
                            <div class="col-4 text-center">
                                <input type="submit" value="Cancel" class="btn btn-warning" asp-controller="MyTravels" asp-action="CancelPost" asp-route-travelId="@Model.Id" asp-route-userId="@this.ViewData["CurrentUserId"]">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <!-- /#page-content-wrapper -->

</div>

CarPooling/CarPooling/Views/MyTravels/CancelTrip.cshtml
@{
    ViewData["Title"] = "Cancel Travel";
    this.ViewData["CurrentUserId"] = this.Context.Session.GetString("CurrentUserId");
}

@model CarPooling.Services.DTOs.PresentDTOs.TravelPresentDTO
<div id="wrapper" class="toggled">

    <!-- Sidebar -->
    <partial name="_Sidebar.cshtml" />
    <!-- /#sidebar-wrapper -->
    <!-- Page Content -->
    <div id="page-content-wrapper">
        <form method="post" asp-action="CancelTripPost" class="text-center form-border">
            <div class="p-4">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group row mt-5">
                    <h1 class="text-primary pb-3 text-center">
                        Cancel Travel
                    </h1>
                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <div class="form-group row">
                            <div class="col d-flex justify-content-center">
                                <label asp-for="StartingPoint">Starting Point</label>
                            </div>
                            <div class="col d-flex justify-content-center">
                                <label asp-for="EndingPoint">Ending Point</label>
                            </div>
                            <div class="col d-flex justify-content-center">
                                <label asp-for="DepartureTime">Departure Time</label>
                            </div>
                            <div class="col d-flex justify-content-center">
                                <label asp-for="FreeSeats">Free Seats</label>
                            </div>
                            <div class="col d-flex justify-content-center">
                                <label asp-for="Status">Status</label>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col p-3">
                                <input asp-for="StartingPoint" disabled class="form-control" />
                            </div>
                            <div class="col p-3">
                                <input asp-for="EndingPoint" disabled class="form-control" />
                            </div>
                            <div class="col p-3">
                                <input asp-for="DepartureTime" disabled class="form-control" />
                                <span asp-validation-for="DepartureTime" class="text-danger"></span>
                            </div>
                            <div class="col p-3">
                                <input asp-for="FreeSeats" disabled class="form-control" />
                            </div>
                            <div class="col p-3">
                                <input asp-for="Status" disabled class="form-control" />
                            </div>
                        </div>

                        <div class="row pt-5">
                            <div class="col-6 text-center">
                                <a asp-controller="Home" asp-action="Index" class="btn btn-secondary">Back to Home</a>
                            </div>
                            <div class="col-4 text-center">
                                <input type="submit" value="Cancel" class="btn btn-danger" asp-controller="MyTravels" asp-action="CancelTripPost" asp-route-travelId="@Model.Id" asp-route-userId="@this.ViewData["CurrentUserId"]">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <!-- /#page-content-wrapper -->

</div>

CarPooling/CarPooling/Views/MyTravels/_Sidebar.cshtml
@{
    this.ViewData["CurrentUserId"] = this.Context.Session.GetString("CurrentUserId");
}

<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <li class="sidebar-brand border-bottom">
            <a asp-area="" asp-controller="MyTravels" asp-action="OrganizedTravels" asp-route-id="@this.ViewData["CurrentUserId"]">
                My Travels
            </a>
        </li>
        <li class="border-bottom">
            <a asp-area="" asp-controller="MyTravels" asp-action="OrganizedTravels" asp-route-id="@this.ViewData["CurrentUserId"]">Organized Travels</a>
        </li>
        <li class="border-bottom">
            <a asp-area="" asp-controller="MyTravels" asp-action="PendingTravels" asp-route-userId="@this.ViewData["CurrentUserId"]">Pending</a>
        </li>
        <li class="border-bottom">
            <a asp-area="" asp-controller="MyTravels" asp-action="ApprovedTravels" asp-route-userId="@this.ViewData["CurrentUserId"]">Approved</a>
        </li>
        <li class="border-bottom">
            <a asp-area="" asp-controller="MyTravels" asp-action="PastOrganizedTravels" asp-route-id="@this.ViewData["CurrentUserId"]">Past Organized Travels</a>
        </li>
        <li class="border-bottom">
            <a asp-area="" asp-controller="MyTravels" asp-action="PastApprovedTravels" asp-route-userId="@this.ViewData["CurrentUserId"]">Past Approved Travels</a>
        </li>
    </ul>
</div>