CarPooling/CarPooling/Controllers/AuthController.cs
using CarPooling.Services.Exceptions;
using CarPooling.Services.Services.Contracts;
using CarPooling.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarPooling.Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService authService;
        private readonly IUserService userService;
        private readonly WebModelMapper webModelMapper;

        public AuthController(IAuthService authService, IUserService userService, WebModelMapper webModelMapper)
        {
            this.authService = authService;
            this.userService = userService;
            this.webModelMapper = webModelMapper;
        }

        //GET /auth/login
        public IActionResult Login()
        {
            var loginViewModel = new LoginViewModel();

            return View(loginViewModel);
        }

        //POST: /auth/login
        [HttpPost]
        public async Task<IActionResult> Login([Bind("Username, Password")] LoginViewModel loginViewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(loginViewModel);
            }

            try
            {
                var user = await this.authService.TryGetUserAsync(loginViewModel.Username, loginViewModel.Password);
                this.HttpContext.Session.SetString("CurrentUser", user.Username);
                this.HttpContext.Session.SetString("CurrentUserId", user.Id.ToString());
                this.HttpContext.Session.SetString("UserFeedbackNavigationId", user.Id.ToString());
                this.HttpContext.Session.SetString("CurrentUserBlockedState", user.IsBlocked.ToString());
                this.HttpContext.Session.SetString("CurrentRoles", string.Join(',', user.Roles.Select(userRole => userRole.Role.Type)));
                this.HttpContext.Session.SetString("ProfilePicture", user.ProfilePicture);

                return this.RedirectToAction("index", "home");
            }
            catch (AuthenticationException e)
            {
                this.ModelState.AddModelError("Username", e.Message);
                return this.View(loginViewModel);
            }
        }

        //GET: /auth/logout
        public IActionResult Logout()
        {
            this.HttpContext.Session.Remove("CurrentUser");
            this.HttpContext.Session.Remove("CurrentRoles");

            return this.RedirectToAction("index", "home");
        }

        //GET /auth/register
        public IActionResult Register()
        {
            var registerViewModel = new RegisterViewModel();
            return View(registerViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Register([Bind("Username, Password, ConfirmPassword, FirstName, LastName, Email, PhoneNumber")] RegisterViewModel registerViewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(registerViewModel);
            }

            try
            {
                this.userService.AlreadyExists(default, registerViewModel.Username, registerViewModel.Email, registerViewModel.PhoneNumber);
            }
            catch (EntityAlreadyExists x)
            {
                this.ModelState.AddModelError("Username", x.Message);
                return this.View(registerViewModel);
            }

            if (!registerViewModel.Password.Equals(registerViewModel.ConfirmPassword))
            {
                this.ModelState.AddModelError("ConfirmPassword", "Confirm password should match password.");
                return this.View(registerViewModel);
            }

            var user = this.webModelMapper.ToModel(registerViewModel);
            await this.userService.CreateAsync(user);

            return this.RedirectToAction(nameof(this.Login));
        }
    }
}

CarPooling/CarPooling/Controllers/FeedbackController.cs
using CarPooling.Data;
using CarPooling.Services.DTOs.CreateDTOs;
using CarPooling.Services.DTOs.PresentDTOs;
using CarPooling.Services.Services.Contracts;
using CarPooling.Web.Helpers;
using CarPooling.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarPooling.Web.Controllers
{
    [CustomAuthorization(Role = "User")]
    public class FeedbackController : Controller
    {
        private readonly IFeedbackService feedbackService;

        public FeedbackController(IFeedbackService feedbackService)
        {
            this.feedbackService = feedbackService;
        }

        public async Task<IActionResult> Index(int userId, string sortOrder, string name, string rating, string comment, int pagenumber = 1)
        {
            var feedbacks = await this.GetFeedbacks(userId, sortOrder, name, rating, comment, pagenumber);

            return this.View(feedbacks);
        }

        public async Task<IActionResult> ViewUserFeedback(int userId, string sortOrder, string name, string rating, string comment, int pagenumber = 1)
        {
            var feedbacks = await this.GetFeedbacks(userId, sortOrder, name, rating, comment, pagenumber);

            return this.View(feedbacks);
        }

        //GET-Create
        public IActionResult CreateFeedback(string toUserId, string travelId)
        {
            ViewBag.ToUserId = toUserId;
            ViewBag.TravelId = travelId;

            var feedback = new FeedbackCreateDTO();

            return this.View(feedback);
        }

        //Post-Create
        [HttpPost]
        public async Task<IActionResult> CreateFeedbackPost(FeedbackCreateDTO feedbackCreate, int travelId, string toUserId)
        {
            if (!this.ModelState.IsValid)
            {
                ViewBag.ToUserId = toUserId;
                ViewBag.TravelId = travelId;

                return this.View("CreateFeedback", feedbackCreate);
            }

            await this.feedbackService.CreateAsync(feedbackCreate, travelId);

            return this.RedirectToAction("Index", "Home");
        }

        private async Task<PaginatedList<FeedbackPresentDTO>> GetFeedbacks(int userId, string sortOrder, string name, string rating, string comment, int pagenumber = 1)
        {
            this.SetViewBags(userId, sortOrder, name, rating, comment);

            var feedbacks = await this.feedbackService.FilterByMultipleCriteria(userId, name, rating, comment);

            feedbacks = Sort(feedbacks, sortOrder);

            return PaginatedList<FeedbackPresentDTO>.Create(feedbacks, pagenumber, 10);
        }

        private void SetViewBags(int userId, string sortOrder, string name, string rating, string comment)
        {
            ViewBag.SortOrder = sortOrder;
            ViewBag.NameSortParm = sortOrder == "name" ? "name_desc" : "name";
            ViewBag.RatingSortParm = string.IsNullOrEmpty(sortOrder) ? "rating_desc" : "";
            ViewBag.Name = name;
            ViewBag.Rating = rating;
            ViewBag.Comment = comment;
            ViewData["UserFeedbackNavigationId"] = userId;
        }

        private static IEnumerable<FeedbackPresentDTO> Sort(IEnumerable<FeedbackPresentDTO> list, string sortOrder)
        {
            list = sortOrder switch
            {
                "name" => list.OrderBy(s => s.FromUser),
                "name_desc" => list.OrderByDescending(s => s.FromUser),
                "rating_desc" => list.OrderByDescending(s => s.Rating),
                _ => list.OrderBy(s => s.Rating),
            };
            return list;
        }
    }
}

CarPooling/CarPooling/Controllers/TravelsController.cs
using CarPooling.Data;
using CarPooling.Services.DTOs.CreateDTOs;
using CarPooling.Services.DTOs.PresentDTOs;
using CarPooling.Services.Exceptions;
using CarPooling.Services.Services.Contracts;
using CarPooling.Web.Helpers;
using CarPooling.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarPooling.Web.Controllers
{
    [CustomAuthorization(Role = "User")]
    public class TravelsController : Controller
    {
        private readonly ITravelService travelService;
        private readonly ICityService cityService;
        private readonly CarPoolingContext carPoolingContext;

        public TravelsController(ITravelService travelService, ICityService cityService, CarPoolingContext carPoolingContext)
        {
            this.travelService = travelService;
            this.cityService = cityService;
            this.carPoolingContext = carPoolingContext;
        }

        public async Task<IActionResult> Index(int id, string sortOrder, string startingCity, string endingCity, 
                                                string user,  DateTime? departureTime, string seats, string preferences, int pagenumber = 1)
        {
            if (!string.IsNullOrEmpty(preferences) && preferences.Contains("select preference", StringComparison.InvariantCultureIgnoreCase))
            {
                preferences = string.Empty;
            }

            ViewBag.Preferences = this.carPoolingContext.Preferences.Select(x => new SelectListItem()
            {
                Text = $"{x.Text}",
                Value = $"{x.Text}"
            });

            var availableTravels = await this.travelService.GetAvailableTravelsAsync(id, "Available");

            var filteredTravels = this.Filter(availableTravels, sortOrder, id, startingCity, endingCity, user, departureTime, seats, preferences, pagenumber);

            return View(filteredTravels);
        }

        private PaginatedList<TravelPresentDTO> Filter(IEnumerable<TravelPresentDTO> travels, 
                                                        string sortOrder, int id, string startingCity, string endingCity, 
                                                        string user, DateTime? departureTime, string seats, string preferences, int pagenumber = 1)
        {
            this.SetViewBags(id, sortOrder, startingCity, endingCity, user, departureTime, seats, preferences);

            var filteredTravels = this.travelService.FilterByMultipleCriteria(travels, startingCity, endingCity, user, departureTime, seats, preferences, default);

            filteredTravels = Sort(filteredTravels, sortOrder);
            
            return PaginatedList<TravelPresentDTO>.Create(filteredTravels, pagenumber, 5);
        }

        private static IEnumerable<TravelPresentDTO> Sort(IEnumerable<TravelPresentDTO> list, string sortOrder)
        {
            list = sortOrder switch
            {
                "name" => list.OrderBy(s => s.CreatedByUser),
                "name_desc" => list.OrderByDescending(s => s.CreatedByUser),
                "startingCity_desc" => list.OrderByDescending(s => s.StartingPoint),
                "endingCity" => list.OrderBy(s => s.EndingPoint),
                "endingCity_desc" => list.OrderByDescending(s => s.EndingPoint),
                "departureTime" => list.OrderBy(s => s.DepartureTime),
                "departureTime_desc" => list.OrderByDescending(s => s.DepartureTime),
                "seats" => list.OrderBy(s => s.FreeSeats),
                "seats_desc" => list.OrderByDescending(s => s.FreeSeats),
                _ => list.OrderBy(s => s.StartingPoint),
            };
            return list;
        }

        private void SetViewBags(int id, string sortOrder, string startingCity, string endingCity, string user, DateTime? departureTime, string seats, string preferences)
        {
            ViewBag.SortOrder = sortOrder;
            ViewBag.StartSort = String.IsNullOrEmpty(sortOrder) ? "startingCity_desc" : "";
            ViewBag.EndSort = sortOrder == "endingCity" ? "endingCity_desc" : "endingCity";
            ViewBag.NameSort = sortOrder == "name" ? "name_desc" : "name";
            ViewBag.DepartureSort = sortOrder == "departureTime" ? "departureTime_desc" : "departureTime";
            ViewBag.SeatSort = sortOrder == "seats" ? "seats_desc" : "seats";
            ViewBag.TravelId = id;
            ViewBag.StartingCity = startingCity;
            ViewBag.EndingCity = endingCity;
            ViewBag.User = user;
            ViewBag.DepartureTime = departureTime;
            ViewBag.Seats = seats;
            ViewBag.Preference = preferences;
        }

        public async Task<IActionResult> Apply(int id)
        {
            var travel = await this.travelService.GetAsync(id);

            return View(travel);
        }

        [HttpPost]
        public async Task<IActionResult> ApplyPost(int travelId, int userId)
        {
            try
            {
                await this.travelService.ApplyUserForTravel(travelId, userId);

                return RedirectToAction("Index", "Home");
            }
            catch (EntityAlreadyExists x)
            {
                var travelToApplyTo = await this.travelService.GetAsync(travelId);
                this.ModelState.AddModelError("DepartureTime", x.Message);
                return this.View("Apply", travelToApplyTo);
            }

        }

        public async Task<IActionResult> CreateNewTravel()
        {
            ViewBag.CityDropDown = await this.cityService.GetCityDropDownAsync();
            ViewBag.Preferences = this.carPoolingContext.Preferences.Select(x => new SelectListItem
            {
                Text = x.Text,
                Value = x.Id.ToString()
            });

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateNewTravelPost(int userId, TravelCreateDTO travelCreateDTO)
        {
            if (!this.ModelState.IsValid)
            {
                ViewBag.CityDropDown = await this.cityService.GetCityDropDownAsync();
                ViewBag.Preferences = this.carPoolingContext.Preferences.Select(x => new SelectListItem
                {
                    Text = x.Text,
                    Value = x.Id.ToString()
                });

                return this.View("CreateNewTravel");
            }

            try
            {
                await this.travelService.CreateAsync(userId, travelCreateDTO);

                return RedirectToAction("Index", "Home");
            }
            catch (DateTimeInPastException x)
            {
                this.ModelState.AddModelError("DepartureTime", x.Message);
                return this.View("CreateNewTravel");
            }

        }
    }
}

CarPooling/CarPooling/Views/Shared/_Carousel.cshtml
<section>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-bs-target="#myCarousel" data-bs-slide-to="0" class="active"></li>
            <li data-bs-target="#myCarousel" data-bs-slide-to="1"></li>
            <li data-bs-target="#myCarousel" data-bs-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item carousel-image-2 active">
                <div class="container-fluid">
                    <div class="carousel-caption mb-5 align-items-center">
                        <h1 class="display-1 mb-4 carousel-heading text-uppercase banner-title about-title">Sharing</h1>
                    </div>
                </div>
            </div>

            <div class="carousel-item carousel-image-1">
                <div class="container-fluid">
                    <div class="carousel-caption mb-5 align-items-center">
                        <h1 class="display-1 mb-4 carousel-heading text-uppercase banner-title about-title">Learning</h1>
                    </div>
                </div>
            </div>

            <div class="carousel-item carousel-image-3">
                <div class="container-fluid">
                    <div class="carousel-caption mb-5 align-items-center">
                        <h1 class="display-1 mb-4 carousel-heading text-uppercase banner-title about-title">Improving</h1>
                    </div>
                </div>
            </div>
        </div>

        <a href="#myCarousel" data-bs-slide="prev" class="carousel-control-prev">
            <span class="carousel-control-prev-icon"></span>
        </a>

        <a href="#myCarousel" data-bs-slide="next" class="carousel-control-next">
            <span class="carousel-control-next-icon"></span>
        </a>
    </div>
</section>

CarPooling/CarPooling/Views/Shared/_Layout.cshtml
@{
    this.ViewData["IsAuthenticated"] = this.Context.Session.Keys.Contains("CurrentUser");
    this.ViewData["CurrentUser"] = this.Context.Session.Get("CurrentUser");
    this.ViewData["CurrentUserId"] = this.Context.Session.GetString("CurrentUserId");
    this.ViewData["ProfilePicture"] = this.Context.Session.GetString("ProfilePicture");
    this.ViewData["CurrentRoles"] = this.Context.Session.GetString("CurrentRoles");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarPooling</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/main.css" />
    <link rel="stylesheet" href="~/css/ratings.css" />
    <link rel="stylesheet" href="~/css/login.css" />
    <link rel="stylesheet" href="~/css/admin.css" />
    <link rel="stylesheet" href="~/css/admin-users.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary p-2 fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand mx-2" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/home-background.jpg" alt="Avatar Logo" style="width:40px;" class="rounded-pill">
                </a>
                <a class="navbar-brand mx-2" asp-area="" asp-controller="Home" asp-action="Index">CarPooling</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse mx-lg-5" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item mx-3">
                            <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">
                                Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item mx-3">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        @if ((bool)this.ViewData["IsAuthenticated"])
                        {
                            <li class="nav-item mx-3">
                                <a class="nav-link" asp-area="" asp-controller="Travels" asp-action="Index" asp-route-id="@this.ViewData["CurrentUserId"]">Travels</a>
                            </li>
                        }
                    </ul>
                    <div class="d-flex">
                        <ul class="navbar-nav me-auto">
                            @if ((bool)this.ViewData["IsAuthenticated"])
                            {
                                <li class="nav-item dropdown mx-2">
                                    <a class="nav-link dropdown-toggle active" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Welcome, @this.Context.Session.GetString("CurrentUser")!</a>
                                    <div class="dropdown-menu  dropdown-menu-end text-center">
                                        <a class="dropdown-item" asp-area="" asp-controller="User" asp-action="Index" asp-route-userId="@this.ViewData["CurrentUserId"]">Update Profile</a>
                                        <a class="dropdown-item" asp-controller="MyTravels" asp-action="OrganizedTravels" asp-route-id="@this.ViewData["CurrentUserId"]">My Travels</a>
                                        <a class="dropdown-item" asp-controller="Feedback" asp-action="Index" asp-route-userId="@this.ViewData["CurrentUserId"]">My Feedbacks</a>
                                        @if (this.ViewData["CurrentRoles"].ToString().Contains("Admin"))
                                        {
                                            <a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="Users">Admin Panel</a>
                                        }
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" asp-controller="Auth" asp-action="Logout">Logout</a>
                                    </div>
                                </li>
                                <li>
                                    <img src="~/profile-pictures/@this.Context.Session.GetString("ProfilePicture")" alt="Avatar Logo" style="width:40px; height:40px" class="rounded-circle">
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-light btn btn-secondary m-1 py-1 px-2" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light btn btn-secondary m-1 py-1 px-2" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid m-0 p-0">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="text-muted bg-primary fixed-bottom text-center p-3 mt-3">
        <div class="container-fluid">
            &copy; @DateTime.Now.Year - CarPooling by <a href="https://www.linkedin.com/in/alexander-taskov-a410bb1a3/" class="text-reset">Aleksander Taskov</a> & <a href="https://www.linkedin.com/in/bogdan-kehayov-5047781a2/" class="text-reset">Bogdan Kehayov</a> - <a asp-area="" asp-controller="Home" asp-action="Index" class="text-reset">Home</a> - <a asp-area="" asp-controller="Home" asp-action="About" class="text-reset">About</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/numscroller/numscroller-1.0.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}